/**
 * Backend-less fallback for the React client.
 *
 * The app is deployable as pure static files, but every read went through
 * `/api/*`, so with no Express host all pages rendered empty. This module
 * serves those reads from the build-time `incidents.json` instead (generated by
 * `script/generate-incidents-json.ts` from `shared/seed-data.ts` — the same
 * dataset the API seeds from, so the numbers cannot drift).
 *
 * Writes (incident submissions, alert sign-ups) and the SPD Blotter RSS proxy
 * genuinely need a server; those surface an explicit error rather than
 * pretending to succeed. See DEPLOYMENT.md.
 */
import { computeStats } from "@shared/stats";
import type { Incident } from "@shared/schema";

export type DataSourceMode =
  /** Still probing, or reads are being served by a live Express backend. */
  | "api"
  /** No backend reachable; reads come from the static incidents.json. */
  | "static"
  /** No backend AND no static dataset — nothing to render. */
  | "unavailable";

export interface DataSourceState {
  mode: DataSourceMode;
  /** ISO timestamp the static dataset was generated, when known. */
  generatedAt?: string;
  /** Human-readable freshness, e.g. "verified 2026-04-17". */
  verifiedLabel?: string;
  /** Why the fallback engaged, for the banner and console. */
  reason?: string;
}

interface StaticDataset {
  schema_version: number;
  dataset_kind: string;
  generated_at: string;
  updated_human?: string;
  stats: ReturnType<typeof computeStats>;
  records: Incident[];
}

let state: DataSourceState = { mode: "api" };
const listeners = new Set<(s: DataSourceState) => void>();

function setState(next: DataSourceState) {
  state = next;
  listeners.forEach((fn) => fn(state));
}

export function getDataSource(): DataSourceState {
  return state;
}

export function subscribeDataSource(fn: (s: DataSourceState) => void): () => void {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

/** Error thrown for reads and writes that cannot be satisfied without a server. */
export class BackendRequiredError extends Error {
  constructor(what: string) {
    super(
      `${what} requires the Express backend, which is not deployed. ` +
        `See DEPLOYMENT.md for what needs to be hosted.`,
    );
    this.name = "BackendRequiredError";
  }
}

let datasetPromise: Promise<StaticDataset> | null = null;

function loadDataset(): Promise<StaticDataset> {
  if (!datasetPromise) {
    // Relative to the document so this works at a domain root and under a
    // GitHub Pages project subpath alike (vite is configured with base "./").
    const url = new URL("incidents.json", document.baseURI).href;
    datasetPromise = fetch(`${url}?t=${Date.now()}`, { cache: "no-store" })
      .then(async (res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status} fetching incidents.json`);
        const data = (await res.json()) as StaticDataset;
        if (!Array.isArray(data.records) || data.records.length === 0) {
          throw new Error("incidents.json contained no records");
        }
        return data;
      })
      .catch((err) => {
        // Let a later call retry instead of caching the failure forever.
        datasetPromise = null;
        throw err;
      });
  }
  return datasetPromise;
}

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

/**
 * Resolve a GET /api/* path from the static dataset.
 * Throws BackendRequiredError for paths that inherently need a server.
 */
export async function staticGet(path: string, reason: string): Promise<Response> {
  const route = path.split("?")[0].replace(/\/+$/, "");

  // These are empty-by-definition without a database, and rendering them as
  // empty lists is honest — there are no stored submissions or subscriptions.
  if (route === "/api/submissions") return jsonResponse([]);
  if (route === "/api/alerts") return jsonResponse([]);

  // The RSS proxy exists to work around CORS; the browser cannot replace it.
  if (route === "/api/spd-blotter") {
    return jsonResponse({
      items: [],
      fetchedAt: new Date().toISOString(),
      error:
        "the SPD Blotter proxy requires the backend, which is not deployed " +
        "(see DEPLOYMENT.md)",
    });
  }

  let dataset: StaticDataset;
  try {
    dataset = await loadDataset();
  } catch (err) {
    setState({
      mode: "unavailable",
      reason: `${reason}; incidents.json also failed to load (${
        err instanceof Error ? err.message : String(err)
      })`,
    });
    throw err;
  }

  if (state.mode !== "static") {
    setState({
      mode: "static",
      generatedAt: dataset.generated_at,
      verifiedLabel: dataset.updated_human,
      reason,
    });
  }

  if (route === "/api/incidents") return jsonResponse(dataset.records);
  if (route === "/api/stats") return jsonResponse(dataset.stats);

  const byId = route.match(/^\/api\/incidents\/(\d+)$/);
  if (byId) {
    const incident = dataset.records.find((r) => r.id === Number(byId[1]));
    return incident
      ? jsonResponse(incident)
      : jsonResponse({ error: "Not found" }, 404);
  }

  throw new BackendRequiredError(`GET ${route}`);
}

export function markBackendReachable() {
  if (state.mode !== "api") setState({ mode: "api" });
}
