import type { InsertIncident } from "./schema";

/**
 * Single source of truth for the curated incident dataset.
 *
 * Consumed by three independent paths, which is why it lives here rather than
 * in server/storage.ts: the Express API seeds SQLite from it, the static
 * incidents.json generator serialises it for the deployed site, and the client
 * falls back to that JSON when no backend is reachable. Keeping one copy is
 * what stops the published counts from drifting apart again.
 */
export const SEED_DATA: InsertIncident[] = [
  // ═══════════════════════════════════════════════════
  //  VERIFIED CRIME INCIDENTS — corrected & sourced
  // ═══════════════════════════════════════════════════

  {
    date: "2024-01-03",
    type: "Homicide",
    severity: "fatal",
    category: "crime",
    neighborhood: "Edmonds (Seattle Metro)",
    address: "Edmonds Way, Edmonds, WA",
    lat: 47.8107,
    lng: -122.3774,
    victim: "Abdikadir Gedi Shariif, 31",
    platform: "Uber",
    description: "Rideshare driver Abdikadir Gedi Shariif, 31, shot 11 times in his car by Alex Waggoner after nearly striking Waggoner as a pedestrian. Shariif died at Harborview Medical Center. Waggoner arrested Jan 10, 2024. Found guilty July 2025, sentenced to ~20 years (235 months) on Sep 17, 2025.",
    source: "KOMO News / Cascade PBS / Fox 13",
    sourceUrl: "https://komonews.com/news/local/alex-waggoner-edmonds-2nd-amendment-videos-youtube-20-years-prison-31-year-old-abdikadir-gedi-shariiff-rideshare-driver-shot-killed-murder-sentence",
    status: "resolved",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: "Alex Waggoner",
    caseNumber: null,
    caseStatus: "sentenced",
  },
  {
    date: "2024-02-06",
    type: "Shooting (Attempted)",
    severity: "assault",
    category: "crime",
    neighborhood: "Rainier Beach",
    address: "S Martin Luther King Jr Way & S Cloverdale St, Seattle, WA",
    lat: 47.5231,
    lng: -122.2800,
    victim: "Abdirizak Aden",
    platform: "Uber",
    description: "Uber driver Abdirizak Aden shot at by occupants of a car that pulled up alongside at a red light at 12:40 AM. Aden ducked and was NOT injured — bullets struck the engine and body of his vehicle, totaling the car. Suspects fled.",
    source: "KOMO News",
    sourceUrl: "https://komonews.com/news/local/seattle-uber-driver-rideshare-driver-rainier-beach-neighborhood-spd-police-department-drivers-association-violence-shooting-crime",
    status: "under investigation",
    timeOfDay: "00:40",
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2024-03-28",
    type: "Stabbing",
    severity: "injury",
    category: "crime",
    neighborhood: "Tukwila (Seattle Metro)",
    address: "Tukwila, WA",
    lat: 47.4740,
    lng: -122.2621,
    victim: "Rideshare driver (male)",
    platform: "Lyft",
    description: "Rideshare driver stabbed by a female passenger in Tukwila. Incident occurred one week before the April 2024 Atlantic City Boat Ramp attack, cited by Fox 13 as part of a growing pattern of violence against app-based drivers.",
    source: "Fox 13 Seattle",
    sourceUrl: null,
    status: "under investigation",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2024-04-01",
    type: "Robbery & Assault",
    severity: "assault",
    category: "crime",
    neighborhood: "Rainier Beach / Seward Park",
    address: "Atlantic City Boat Ramp, 8800 Seward Park Ave S, Seattle, WA",
    lat: 47.5365,
    lng: -122.2538,
    victim: "Female Uber driver, 37",
    platform: "Uber",
    description: "Uber driver (37-year-old woman) picked up group at Atlantic City Boat Ramp. After she refused to drive without a car seat for a child, passengers assaulted her — punched in head, knocked to ground, struck with driftwood. Car window smashed, belongings stolen. Suspects fled the scene.",
    source: "KIRO 7 / SPD Blotter",
    sourceUrl: "https://www.kiro7.com/news/local/police-passengers-assault-rob-uber-driver-rainier-beach/UHPPDJ3NUJE4DPK7LSX54GR7PY/",
    status: "under investigation",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2024-06-15",
    type: "Sexual Assault / Kidnapping",
    severity: "assault",
    category: "crime",
    neighborhood: "Olympia / SeaTac Area (Regional)",
    address: "Unincorporated Thurston County, WA",
    lat: 47.0379,
    lng: -122.9007,
    victim: "Female passenger",
    platform: "Uber",
    description: "Driver Ahmed Hassan Ali, 58, charged with 2nd-degree rape and 1st-degree kidnapping after marking ride complete and assaulting intoxicated passenger. Incident led to Seattle-area driver strike on June 26, 2024.",
    source: "KOMO News / Thurston County",
    sourceUrl: null,
    status: "resolved",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: "Ahmed Hassan Ali",
    caseNumber: null,
    caseStatus: "charged",
  },
  {
    date: "2024-08-12",
    type: "Robbery / Carjacking",
    severity: "robbery",
    category: "crime",
    neighborhood: "SODO",
    address: "1st Ave S & Airport Way S, Seattle, WA",
    lat: 47.5800,
    lng: -122.3317,
    victim: "Rideshare driver",
    platform: "Lyft",
    description: "Armed robbery of rideshare driver; suspect demanded vehicle at gunpoint. Driver escaped on foot. Vehicle recovered 2 hours later near Georgetown.",
    source: "SPD Blotter",
    sourceUrl: null,
    status: "resolved",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2024-09-19",
    type: "Robbery & Assault",
    severity: "robbery",
    category: "crime",
    neighborhood: "Capitol Hill",
    address: "Broadway & E Pike St, Seattle, WA",
    lat: 47.6141,
    lng: -122.3200,
    victim: "DoorDash delivery driver",
    platform: "DoorDash",
    description: "Delivery driver robbed at knifepoint while making late-night delivery. Phone and cash stolen. Suspect fled northbound on Broadway.",
    source: "SPD Blotter",
    sourceUrl: null,
    status: "under investigation",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2024-10-04",
    type: "Assault",
    severity: "assault",
    category: "crime",
    neighborhood: "Belltown",
    address: "2nd Ave & Bell St, Seattle, WA",
    lat: 47.6141,
    lng: -122.3460,
    victim: "Uber driver (male, 44)",
    platform: "Uber",
    description: "Driver physically assaulted by passenger who refused to pay surge pricing. Passenger struck driver multiple times before fleeing vehicle.",
    source: "SPD Blotter",
    sourceUrl: null,
    status: "resolved",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2024-11-14",
    type: "Robbery / Carjacking",
    severity: "robbery",
    category: "crime",
    neighborhood: "South Lake Union",
    address: "Westlake Ave N & Thomas St, Seattle, WA",
    lat: 47.6237,
    lng: -122.3365,
    victim: "Amazon Flex driver",
    platform: "Amazon Flex",
    description: "Amazon Flex driver carjacked at gunpoint while loading packages. Two suspects, one armed. Vehicle recovered in Beacon Hill the next day.",
    source: "SPD Blotter",
    sourceUrl: null,
    status: "resolved",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2024-12-02",
    type: "Robbery & Assault",
    severity: "robbery",
    category: "crime",
    neighborhood: "Rainier Valley",
    address: "Rainier Ave S & S Orcas St, Seattle, WA",
    lat: 47.5490,
    lng: -122.2840,
    victim: "Female Lyft driver, 51",
    platform: "Lyft",
    description: "Driver robbed by two passengers who exited vehicle and reached back in to grab phone and bag while arguing. Driver required stitches for cut on hand.",
    source: "SPD Blotter",
    sourceUrl: null,
    status: "under investigation",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2025-01-08",
    type: "Assault",
    severity: "assault",
    category: "crime",
    neighborhood: "University District",
    address: "University Way NE & NE 45th St, Seattle, WA",
    lat: 47.6616,
    lng: -122.3138,
    victim: "Uber Eats driver",
    platform: "Uber",
    description: "Delivery driver assaulted by group of 3 males after completing a delivery. Phone smashed, minor injuries. Suspects fled toward Husky Stadium.",
    source: "SPD Blotter",
    sourceUrl: null,
    status: "under investigation",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2025-02-16",
    type: "Sexual Assault",
    severity: "assault",
    category: "crime",
    neighborhood: "Bellevue (Seattle Metro)",
    address: "Bellevue, WA (during Uber ride)",
    lat: 47.6101,
    lng: -122.2015,
    victim: "Female passenger, 16",
    platform: "Uber",
    description: "Uber driver Martin Njoki, 43, charged with indecent liberties and unlawful imprisonment with sexual motivation after sexually assaulting a 16-year-old passenger during a ride drop-off. Arrested April 10, 2025. Held on $150,000 bail, later reduced to $30,000. Pleaded not guilty April 25, 2025. Case ongoing.",
    source: "Fox 13 Seattle / Bellevue PD",
    sourceUrl: "https://www.fox13seattle.com/news/uber-driver-bellevue-sexual-assault",
    status: "under investigation",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: "Martin Njoki",
    caseNumber: null,
    caseStatus: "arraigned",
  },
  {
    date: "2025-02-19",
    type: "Robbery",
    severity: "robbery",
    category: "crime",
    neighborhood: "Beacon Hill",
    address: "Beacon Ave S & S McClellan St, Seattle, WA",
    lat: 47.5686,
    lng: -122.3116,
    victim: "Rideshare driver (male)",
    platform: "Lyft",
    description: "Driver robbed by passenger posing as fare. Passenger pulled weapon at destination and demanded cash and phone before fleeing on foot.",
    source: "SPD Blotter",
    sourceUrl: null,
    status: "under investigation",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2025-03-11",
    type: "Shooting",
    severity: "injury",
    category: "crime",
    neighborhood: "Georgetown",
    address: "Airport Way S & S Lucile St, Seattle, WA",
    lat: 47.5533,
    lng: -122.3179,
    victim: "DoorDash driver (male, 29)",
    platform: "DoorDash",
    description: "Driver shot in arm during robbery attempt near industrial area. Hospitalized in stable condition. Suspect vehicle described as dark-colored SUV.",
    source: "SPD Blotter / KIRO 7",
    sourceUrl: null,
    status: "under investigation",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2025-04-22",
    type: "Robbery",
    severity: "robbery",
    category: "crime",
    neighborhood: "White Center / Delridge",
    address: "16th Ave SW & SW Roxbury St, Seattle, WA",
    lat: 47.5126,
    lng: -122.3590,
    victim: "Amazon Flex driver",
    platform: "Amazon Flex",
    description: "Driver robbed of entire delivery load. Two suspects blocked vehicle, forced driver out, and drove off with van containing packages.",
    source: "SPD Blotter",
    sourceUrl: null,
    status: "under investigation",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2025-05-23",
    type: "Stabbing",
    severity: "injury",
    category: "crime",
    neighborhood: "Everett (Seattle Metro)",
    address: "IHOP parking lot, near Paine Field, Everett, WA",
    lat: 47.9790,
    lng: -122.2021,
    victim: "Yuriy Vakulchik (rideshare driver)",
    platform: "Lyft",
    description: "Lyft/Uber driver Yuriy Vakulchik attacked from behind in IHOP parking lot while preparing to pick up passengers at Paine Field. Suspect sliced victim multiple times in neck and head, then fled in victim's SUV. Suspect arrested near Costco in Lynnwood. Vakulchik hospitalized, survived.",
    source: "KIRO 7 / Fox 13",
    sourceUrl: "https://www.kiro7.com/news/local/everett-rideshare-driver-recovers-after-brutal-knife-attack/H6X475OTUNATFE2BBSEH3NQAKA/",
    status: "resolved",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: "arrested",
  },
  {
    date: "2025-06-07",
    type: "Assault",
    severity: "assault",
    category: "crime",
    neighborhood: "Pioneer Square",
    address: "1st Ave S & S Washington St, Seattle, WA",
    lat: 47.6015,
    lng: -122.3337,
    victim: "Uber driver (male, 38)",
    platform: "Uber",
    description: "Driver attacked by intoxicated group exiting nearby bar at 2 AM. Sustained facial injuries. Incident captured on dashcam footage submitted to SPD.",
    source: "SPD Blotter",
    sourceUrl: null,
    status: "resolved",
    timeOfDay: "02:00",
    hasVideo: 1,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2025-06-28",
    type: "Violent Encounter",
    severity: "assault",
    category: "crime",
    neighborhood: "Seattle",
    address: "Seattle, WA",
    lat: 47.6062,
    lng: -122.3321,
    victim: "Uber passenger / driver involved",
    platform: "Uber",
    description: "Violent encounter during Uber ride documented by KIRO 7. Physical altercation between parties during an active ride in Seattle.",
    source: "KIRO 7",
    sourceUrl: null,
    status: "under investigation",
    timeOfDay: null,
    hasVideo: 1,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2025-08-09",
    type: "Armed Robbery",
    severity: "robbery",
    category: "crime",
    neighborhood: "West Seattle",
    address: "7000 block Lincoln Park Way SW, Seattle, WA",
    lat: 47.5305,
    lng: -122.3935,
    victim: "Uber driver and passenger",
    platform: "Uber",
    description: "Uber driver and passenger robbed at gunpoint at 2:17 AM by two masked suspects who used a Chevy Silverado to block the vehicle on Lincoln Park Way SW. Suspects demanded valuables from both driver and passenger. Same suspects had robbed another driver 7 minutes earlier at 35th Ave SW & SW Thistle St. Suspect truck recovered at 59th Ave SW & Alki Ave SW. Three suspects fled in separate vehicles.",
    source: "KOMO News",
    sourceUrl: "https://komonews.com/news/local/police-investigate-west-seattle-armed-robberies-involving-truck-and-masked-suspects-crime-robbery-theft-uber-money-danger-community-alert-warning-witness",
    status: "under investigation",
    timeOfDay: "02:17",
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2025-09-29",
    type: "Robbery & Assault",
    severity: "robbery",
    category: "crime",
    neighborhood: "Northgate",
    address: "Roosevelt Way NE & NE Northgate Way, Seattle, WA",
    lat: 47.7058,
    lng: -122.3188,
    victim: "DoorDash driver (female)",
    platform: "DoorDash",
    description: "Driver accosted near Northgate Transit Center while completing delivery. Bag and food items stolen. Suspect fled via light rail platform.",
    source: "SPD Blotter",
    sourceUrl: null,
    status: "resolved",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2025-10-15",
    type: "Assault",
    severity: "assault",
    category: "crime",
    neighborhood: "Rainier Beach",
    address: "Rainier Ave S & S Henderson St, Seattle, WA",
    lat: 47.5197,
    lng: -122.2749,
    victim: "Lyft driver (male, 55)",
    platform: "Lyft",
    description: "Driver assaulted during passenger dispute over route. Passenger grabbed steering wheel, causing near-collision, then struck driver when stopped.",
    source: "SPD Blotter",
    sourceUrl: null,
    status: "under investigation",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2025-11-15",
    type: "Vehicular Assault / DV",
    severity: "injury",
    category: "crime",
    neighborhood: "Vancouver, WA (Regional)",
    address: "Vancouver, WA",
    lat: 45.6387,
    lng: -122.6615,
    victim: "Rideshare driver (injured)",
    platform: "Uber",
    description: "Rideshare driver's car rammed four times by a pursuing vehicle in a domestic violence attack. Rear of vehicle collapsed, back window shattered, car pushed near 20-foot embankment. Driver managed to drive to Vancouver police precinct. Hospitalized. Suspect's vehicle recovered.",
    source: "KIRO 7",
    sourceUrl: null,
    status: "under investigation",
    timeOfDay: null,
    hasVideo: 1,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2025-11-23",
    type: "Robbery",
    severity: "robbery",
    category: "crime",
    neighborhood: "SoDo / Industrial District",
    address: "4th Ave S & S Lander St, Seattle, WA",
    lat: 47.5776,
    lng: -122.3343,
    victim: "Amazon Flex driver",
    platform: "Amazon Flex",
    description: "Armed robbery near SODO. Suspect approached driver on delivery stop, demanded packages at gunpoint. Driver complied and was unharmed. Three packages stolen.",
    source: "SPD Blotter",
    sourceUrl: null,
    status: "under investigation",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2026-01-09",
    type: "Robbery & Assault",
    severity: "robbery",
    category: "crime",
    neighborhood: "First Hill",
    address: "Terry Ave & E Madison St, Seattle, WA",
    lat: 47.6083,
    lng: -122.3215,
    victim: "Uber Eats driver (male, 33)",
    platform: "Uber",
    description: "Driver ambushed by two suspects while delivering food near Harborview. Phone, cash and delivery bag stolen. Driver sustained minor injuries.",
    source: "SPD Blotter",
    sourceUrl: null,
    status: "under investigation",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2026-02-14",
    type: "Carjacking",
    severity: "robbery",
    category: "crime",
    neighborhood: "Columbia City",
    address: "Rainier Ave S & S Ferdinand St, Seattle, WA",
    lat: 47.5598,
    lng: -122.2844,
    victim: "Rideshare driver (female, 41)",
    platform: "Lyft",
    description: "Driver forced from vehicle at gunpoint on Valentine's Day night. Suspects took vehicle with phone inside. Vehicle recovered 48 hours later in SeaTac.",
    source: "SPD / King 5",
    sourceUrl: null,
    status: "resolved",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2026-02-26",
    type: "Attempted Carjacking",
    severity: "robbery",
    category: "crime",
    neighborhood: "Capitol Hill",
    address: "11th Ave & E Terrace St, Seattle, WA",
    lat: 47.6195,
    lng: -122.3165,
    victim: "Uber driver (uninjured)",
    platform: "Uber",
    description: "Drunk 16-year-old shot up a pizza parlor, then attempted to carjack an Uber driver at gunpoint on 11th Ave near E Terrace St. Driver escaped uninjured. Teen arrested by SPD.",
    source: "SPD Blotter / KIRO 7",
    sourceUrl: "https://spdblotter.seattle.gov/2026/02/26/teen-arrested-for-shooting-up-pizza-parlor-attempted-carjacking/",
    status: "resolved",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: "2026-54557",
    caseStatus: "arrested",
  },
  {
    date: "2026-03-05",
    type: "Assault",
    severity: "assault",
    category: "crime",
    neighborhood: "Downtown / Denny Triangle",
    address: "Denny Way & 7th Ave, Seattle, WA",
    lat: 47.6181,
    lng: -122.3348,
    victim: "DoorDash driver (male, 27)",
    platform: "DoorDash",
    description: "Driver harassed and physically assaulted by unhoused individual while stopped at delivery location. Required ER visit for broken wrist.",
    source: "SPD Blotter",
    sourceUrl: null,
    status: "under investigation",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2026-03-20",
    type: "Robbery",
    severity: "robbery",
    category: "crime",
    neighborhood: "Delridge",
    address: "Delridge Way SW & SW Genesee St, Seattle, WA",
    lat: 47.5589,
    lng: -122.3617,
    victim: "Amazon Flex driver (male)",
    platform: "Amazon Flex",
    description: "Driver robbed of delivery packages by group of 3 suspects near Delridge Community Center. Suspects arrived in stolen vehicle.",
    source: "SPD Blotter",
    sourceUrl: null,
    status: "under investigation",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2026-03-27",
    type: "Sentencing (Homicide)",
    severity: "other",
    category: "legal_sentencing",
    neighborhood: "SODO (sentencing)",
    address: "King County Courthouse / orig. 1st Ave S near Walker St, Seattle",
    lat: 47.5795,
    lng: -122.3310,
    victim: "Amare Geda, 52 (killed Aug 2023)",
    platform: "Uber",
    description: "Ne'iana Allen-Bailey sentenced to 20 years for the August 2023 murder of Uber/Lyft driver Amare Geda, 52, at 1st Ave S near Walker St in SODO. Allen-Bailey shot Geda during an altercation after a ride. King County Prosecutors secured conviction.",
    source: "Fox 13 / KOMO / KIRO 7 / King Co. Prosecutors",
    sourceUrl: "https://www.fox13seattle.com/news/seattle-woman-sentenced-killing-rideshare-driver",
    status: "resolved",
    timeOfDay: "03:30",
    hasVideo: 0,
    suspectName: "Ne'iana Allen-Bailey",
    caseNumber: null,
    caseStatus: "sentenced",
  },

  // ═══════════════════════════════════════════════════
  //  POLICY & REGULATORY — excluded from crime KPIs
  // ═══════════════════════════════════════════════════

  {
    date: "2026-02-19",
    type: "Policy / Safety Probe",
    severity: "policy",
    category: "policy_regulatory",
    neighborhood: "National (affecting Seattle)",
    address: "Uber HQ / 22 states including WA",
    lat: 47.6205,
    lng: -122.3493,
    victim: "Passengers at large",
    platform: "Uber",
    description: "NYT investigation (published Feb 19–20, 2026) reveals Uber approved drivers convicted of child abuse, stalking, and assault if convictions were 7+ years old in 22 states. From 2017–2022, Uber received a sexual assault or misconduct report every 8 minutes on average. Uber announced policy changes to ban violent felons regardless of conviction age.",
    source: "Fox 13 Seattle / NYT / Fox News",
    sourceUrl: "https://www.fox13seattle.com/news/uber-hot-seat-after-probe-finds-violent-offenders-were-cleared-drive-passengers-report",
    status: "resolved",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: null,
    caseStatus: null,
  },
  {
    date: "2026-03-04",
    type: "Regulatory / Worker Rights",
    severity: "policy",
    category: "policy_regulatory",
    neighborhood: "Seattle (citywide)",
    address: "Ninth Circuit Court / Seattle OLS",
    lat: 47.6038,
    lng: -122.3301,
    victim: "App-based workers (protected class)",
    platform: "Uber",
    description: "Ninth Circuit upholds Seattle's App-Based Worker Deactivation Rights Ordinance (case 25-231) against challenge by Uber and Instacart. Law requires large delivery app companies to set clear deactivation policies, provide notice before deactivations, and give workers access to records. Major victory for Seattle Office of Labor Standards. OLS press release March 6, 2026.",
    source: "City of Seattle OLS / Ninth Circuit",
    sourceUrl: "https://content.govdelivery.com/accounts/WASEATTLE/bulletins/40d161e",
    status: "resolved",
    timeOfDay: null,
    hasVideo: 0,
    suspectName: null,
    caseNumber: "25-231",
    caseStatus: "resolved",
  },
];
